### PR TITLE
Add multi prompt feature, ability to save to google drive, some small imporvments

### PR DESCRIPTION
**Pull request by v8hid**

### CODE REVIEW

**Comment by BalintKomjati** [comment]
Hi @v8hid ! 
Sorry for not coming back earlier, just noticed your PR.
I would be very happy to merge but also seen you made additional improvements as well.
I think it would make more sense to join forces and merge them all. 
What do you think?

**Comment by BalintKomjati** [comment]
Hi again! 

The reason of my lag in the first place is that i am occupied with an other project, and have an other one booked ahead. So for the following 1-2 months I will not have time to actually develop something. 

But reviewing a PR with your recent devs is fully OK and would be very much appreciated!! :) 

Still I would like to get back to this project later on, especially in a collaboration setting! :) I am particularly excited about your auto1111 integration as well as about your other progress.

The most interesting ideas i have in mind are 
 - upscaling the video to 1024 (this is started in a separate branch but abandoned due to time constrains after pulling together the first proto which works but the output is distorted ... it is the only branch of my repo so you will find it easily)
 - make it possible to drift between prompts e.g. start with an ancient image and gradually zoom into modern times. how cool that would be? :D

**Comment by v8hid** [comment]
Thanks for getting back to me! I'm glad to hear that you're happy with my changes and interested in collaborating on future improvements. Since you're busy with other projects at the moment, I'll create a new PR from the latest version of my fork and you can review it whenever you have time. Once you've had a chance to review it, we can close this one and merge the changes.

I completely agree that upscaling the video would be a great addition, and I'm looking forward to working on that in the future. As for the ability to drift between prompts, I actually already achieved this feature, and I think it would be really cool to see it in action.

Lastly, I wanted to share with you that my extension for Automatic1111 is now ready to use. You can check it out at [HERE](https://github.com/v8hid/infinite-zoom-automatic1111-webui). Let me know if you have any feedback or suggestions for improvement.

**Comment by BalintKomjati** [comment]
Is your "drift btw prompts" available somewhere? (colab would be the best for me) I would love to play with that :) 

Yes, please create a fresh all-in PR! :)

A1111 integration is very cool, congrats!! 👍

**Comment by v8hid** [comment]
I explained the feature you mentioned in [this comment](https://github.com/v8hid/infinite-zoom-automatic1111-webui/issues/7#issuecomment-1509352636) 
Thank you, I'm glad you find the extension interesting.
I created the PR yesterday I will close this one.

**Comment by BalintKomjati** [comment]
Cool, thanks! 

A more elegant way to drift between prompts would be (at least this is what excites me) to **gradually** shift between words using weights (or attention, i'm not sure about the jargon)  

E.g. Prompt = "[Stone age:w1] [Medieval:w2] [Futuristic:w3] vehicle" 
Start with w1 = 1, w2 = 0, w3 =0, and sequentially decrease w1 while increasing w2 ...

I could not get around this so opened a SO question, but received the answer too late when i was already away from the topic :)
https://stackoverflow.com/questions/75355037/how-to-define-prompt-weights-to-huggingfaces-diffusers-stablediffusioninpaintpi

**Comment by v8hid** [comment]
Oh, now I got your meaning, would be so cool, I will add this to my feature list.

**Pull request closed without merging**
